package se.adventsapp;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

import java.util.Arrays;

import org.junit.Test;

public class KeypadTest {

	// 123
	// 456
	// 789
	
	@Test
	public void enNyKeypadHarNummer5NärDenÄrNy() {

		Keypad keypad = new Keypad();
		
		assertThat(keypad.getCurrentKey(), is(5));
	}
	
	@Test
	public void enKeypadKanTaKommandon(){
		
		Keypad keypad = new Keypad();
		
		keypad.moveCommand("U");
		assertThat(keypad.getCurrentKey(), is(2));
		keypad.moveCommand("R");
		assertThat(keypad.getCurrentKey(), is(3));
		keypad.moveCommand("D");
		assertThat(keypad.getCurrentKey(), is(6));
		keypad.moveCommand("L");
		keypad.moveCommand("L");
		assertThat(keypad.getCurrentKey(), is(4));
		keypad.moveCommand("L");
		assertThat(keypad.getCurrentKey(), is(4));
	
	}
	
	@Test
	public void testaEnListaMedKommandon(){
		
		Keypad keypad = new Keypad();
		
		String commandoLista1 = "ULL";
		String commandoLista2 = "RRDDD";
		String commandoLista3 = "LURDL";
		String commandoLista4 = "UUUUD";
		
		keypad.moveCommandList(Arrays.asList(commandoLista1.split("")));
		assertThat(keypad.getCurrentKey(), is(1));
		keypad.moveCommandList(Arrays.asList(commandoLista2.split("")));
		assertThat(keypad.getCurrentKey(), is(9));
		keypad.moveCommandList(Arrays.asList(commandoLista3.split("")));
		assertThat(keypad.getCurrentKey(), is(8));
		keypad.moveCommandList(Arrays.asList(commandoLista4.split("")));
		assertThat(keypad.getCurrentKey(), is(5));
		
		
	}
	
	@Test
	public void problem2(){
		Keypad keypad = new Keypad();
		
		String commandoLista1 = "DLUUULUDLRDDLLLUDULLULLRUURURLUULDUUUDLDDRUDLUULLRLDDURURDDRDRDLDURRURDLDUURULDDULDRDDLDLDLRDRUURLDLUDDDURULRLLLLRLULLUDRDLDUURDURULULULRLULLLULURLRDRDDDDDDDLRLULUULLULURLLDLRLUDULLDLLURUDDLDULDLULDDRLRLRDDLRURLLLURRLDURRDLLUUUUDRURUULRLDRRULLRUDLDRLUDRDRDRRDDURURRDRDRUDURDLUDRUDLRRULDLRDDRURDDUUDLDRDULDDRRURLLULRDRURLRLDLLLUULUUDLUDLDRRRRDUURULDUDUDRLDLLULLLRDDDDDLRDDLLUULLRRRDURLRURDURURLUDRRLRURDRDRRRRULUDLDRDULULRUDULLLUDRRLRLURDDURULDUUDULLURUULRDRDULRUUUDURURDDRRUDURRLRDRULRUUU";
		String commandoLista2 = "LDRURRUUUULDRDDDLLULDRUDDRLLDLDRDLRUDDDLDDULULULLRULDUDRRDLRUURURDRURURDLLRUURDUUDRLDURDRDLRRURURDUUUURUURRLLLDRDUURRRRURULUUUDLUDDRUURRLDULRDULRRRRUDURRLURULRURRDRDLLDRRDUDRDURLDDRURULDRURUDDURDLLLUURRLDRULLURDRDRLDRRURRLRRRDDDDLUDLUDLLDURDURRDUDDLUDLRULRRRDRDDLUDRDURDRDDUURDULRRULDLDLLUDRDDUDUULUDURDRLDURLRRDLDDLURUDRLDUURLLRLUDLLRLDDUDLLLRRRLDLUULLUDRUUDRLDUUUDUURLRDDDDRRDRLDDRDLUDRULDDDRDUULLUUUUULDULRLLLRLLDULRDUDDRDDLRRLRDDULLDURRRURDDUDUDDRLURRLUUUULLDRDULUUDRDULDLLUDLURDLLURRDLUULURRULRLURRRRRUURDDURLRLLDDLRRDUUURDRDUDRDDDLLDDRDRRRLURRDUULULULULRRURDDLDDLLLRUDDDDDDLLLRDULURULLRLRDRR";
		String commandoLista3 = "DDRLLLDLRRURRDLDDRUURRURRLRRRRUURUURDLURRRDDLRUDRURLUURLLRRLRLURLURURDULLLLDLRURULUUDURRLULRDRDRRDDLLULRLUDLUUUDRLLRRURRLDULDDLRRLUUUUDDLRLDRLRRDRDLDDURDDRDDLDLURLRRRDDUDLLRLRLURRRRULLULLLLDRLDULDLLDULRLDRDLDDRRDDDDRUDRLLURULRLDDLLRRURURDDRLLLULLULDDRDLDDDLRLLDRLDRUURRULURDDRLULLDUURRULURUUDULLRUDDRRLLDLLRDRUDDDDLLLDDDLLUUUULLDUUURULRUUDUUUDDLDURLDRDRRLLUDULDLUDRLLLDRRRULUUDDURUDRLUDDRRLLDUDUURDDRURLUURDURURURRUUDUDDLLLDRRRURURRURDLRULLDUDRLRLLRUDRUDLR";
		String commandoLista4 = "RRRDRLRURLRRLUURDRLDUURURLRDRRUDLLUUDURULLUURDLLDRRLURRUDUUDRRURLRRDULLDDLRRRUDUUDUUDLDDDLUUDLDULDDULLDUUUUDDUUDUDULLDDURRDLRRUDUDLRDUULDULRURRRLDLLURUDLDDDRRLRDURDLRRLLLRUDLUDRLLLRLLRRURUDLUDURLDRLRUDLRUULDRULLRLDRDRRLDDDURRRUDDDUDRRDRLDDRDRLLRLLRDLRDUDURURRLLULRDRLRDDRUULRDDRLULDLULURDLRUDRRDDDLDULULRDDRUDRLRDDRLDRDDRRRDUURDRLLDDUULRLLLULLDRDUDRRLUUURLDULUUURULLRLUDLDDLRRDLLRDDLRDRUUDURDDLLLDUUULUUDLULDUDULDRLRUDDURLDDRRRDLURRLLRRRUDDLDDRURDUULRUURDRRURURRRUUDUDULUDLUDLLLUUUULRLLRRRRDUDRRDRUDURLUDDLDRDLDDRULLRRULDURUL";
		String commandoLista5 = "DLLLRDDURDULRRLULURRDULDLUDLURDDURRLLRRLLULRDLDRDULRLLRDRUUULURRRLLRLDDDRDRRULDRRLLLLDLUULRRRURDDRULLULDDDLULRLRRRUDRURULUDDRULDUDRLDRRLURULRUULLLRUURDURLLULUURUULUUDLUDLRRULLLRRLRURDRRURDRULRURRUDUDDDRDDULDLURUDRDURLDLDLUDURLLRUULLURLDDDURDULRLUUUDLLRRLLUURRDUUDUUDUURURDRRRRRRRRRUDULDLULURUDUURDDULDUDDRDDRDRLRUUUUDLDLRDUURRLRUUDDDDURLRRULURDUUDLUUDUUURUUDRURDRDDDDULRLLRURLRLRDDLRUULLULULRRURURDDUULRDRRDRDLRDRRLDUDDULLDRUDDRRRD";

		keypad.moveCommandList(Arrays.asList(commandoLista1.split("")));
		System.out.println("Code 1: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista2.split("")));
		System.out.println("Code 2: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista3.split("")));
		System.out.println("Code 3: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista4.split("")));
		System.out.println("Code 4: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista5.split("")));
		System.out.println("Code 5: " + keypad.getCurrentKey());
		
		
	}
	
}
