package se.adventsapp;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

import java.util.Arrays;

import org.junit.Test;

public class Keypad13DigitsTest {

	// 123
	// 456
	// 789
	
	@Test
	public void enNyKeypadHarNummer5NärDenÄrNy() {

		Keypad13Digits keypad = new Keypad13Digits();
		
		assertThat(keypad.getCurrentKey(), is('5'));
	}
	
	@Test
	public void enKeypadKanTaKommandon(){
		
		Keypad13Digits keypad = new Keypad13Digits();
		
		keypad.moveCommand("R");
		assertThat(keypad.getCurrentKey(), is('6'));
		keypad.moveCommand("U");
		assertThat(keypad.getCurrentKey(), is('2'));
		keypad.moveCommand("D");
		assertThat(keypad.getCurrentKey(), is('6'));
		keypad.moveCommand("R");
		keypad.moveCommand("R");
		assertThat(keypad.getCurrentKey(), is('8'));
		keypad.moveCommand("D");
		assertThat(keypad.getCurrentKey(), is('C'));
		keypad.moveCommand("D");
		assertThat(keypad.getCurrentKey(), is('C'));
		keypad.moveCommand("L");
		assertThat(keypad.getCurrentKey(), is('B'));
		keypad.moveCommand("L");
		assertThat(keypad.getCurrentKey(), is('A'));
	
	}
	
	@Test
	public void testaEnListaMedKommandon(){
		
		Keypad13Digits keypad = new Keypad13Digits();
		
		String commandoLista1 = "ULL";
		String commandoLista2 = "RRDDD";
		String commandoLista3 = "LURDL";
		String commandoLista4 = "UUUUD";
		
		keypad.moveCommandList(Arrays.asList(commandoLista1.split("")));
		assertThat(keypad.getCurrentKey(), is('5'));
		keypad.moveCommandList(Arrays.asList(commandoLista2.split("")));
		assertThat(keypad.getCurrentKey(), is('D'));
		keypad.moveCommandList(Arrays.asList(commandoLista3.split("")));
		assertThat(keypad.getCurrentKey(), is('B'));
		keypad.moveCommandList(Arrays.asList(commandoLista4.split("")));
		assertThat(keypad.getCurrentKey(), is('3'));
		
		
	}
	
	@Test
	public void problem2(){
		Keypad13Digits keypad = new Keypad13Digits();
		
		String commandoLista1 = "DLUUULUDLRDDLLLUDULLULLRUURURLUULDUUUDLDDRUDLUULLRLDDURURDDRDRDLDURRURDLDUURULDDULDRDDLDLDLRDRUURLDLUDDDURULRLLLLRLULLUDRDLDUURDURULULULRLULLLULURLRDRDDDDDDDLRLULUULLULURLLDLRLUDULLDLLURUDDLDULDLULDDRLRLRDDLRURLLLURRLDURRDLLUUUUDRURUULRLDRRULLRUDLDRLUDRDRDRRDDURURRDRDRUDURDLUDRUDLRRULDLRDDRURDDUUDLDRDULDDRRURLLULRDRURLRLDLLLUULUUDLUDLDRRRRDUURULDUDUDRLDLLULLLRDDDDDLRDDLLUULLRRRDURLRURDURURLUDRRLRURDRDRRRRULUDLDRDULULRUDULLLUDRRLRLURDDURULDUUDULLURUULRDRDULRUUUDURURDDRRUDURRLRDRULRUUU";
		String commandoLista2 = "LDRURRUUUULDRDDDLLULDRUDDRLLDLDRDLRUDDDLDDULULULLRULDUDRRDLRUURURDRURURDLLRUURDUUDRLDURDRDLRRURURDUUUURUURRLLLDRDUURRRRURULUUUDLUDDRUURRLDULRDULRRRRUDURRLURULRURRDRDLLDRRDUDRDURLDDRURULDRURUDDURDLLLUURRLDRULLURDRDRLDRRURRLRRRDDDDLUDLUDLLDURDURRDUDDLUDLRULRRRDRDDLUDRDURDRDDUURDULRRULDLDLLUDRDDUDUULUDURDRLDURLRRDLDDLURUDRLDUURLLRLUDLLRLDDUDLLLRRRLDLUULLUDRUUDRLDUUUDUURLRDDDDRRDRLDDRDLUDRULDDDRDUULLUUUUULDULRLLLRLLDULRDUDDRDDLRRLRDDULLDURRRURDDUDUDDRLURRLUUUULLDRDULUUDRDULDLLUDLURDLLURRDLUULURRULRLURRRRRUURDDURLRLLDDLRRDUUURDRDUDRDDDLLDDRDRRRLURRDUULULULULRRURDDLDDLLLRUDDDDDDLLLRDULURULLRLRDRR";
		String commandoLista3 = "DDRLLLDLRRURRDLDDRUURRURRLRRRRUURUURDLURRRDDLRUDRURLUURLLRRLRLURLURURDULLLLDLRURULUUDURRLULRDRDRRDDLLULRLUDLUUUDRLLRRURRLDULDDLRRLUUUUDDLRLDRLRRDRDLDDURDDRDDLDLURLRRRDDUDLLRLRLURRRRULLULLLLDRLDULDLLDULRLDRDLDDRRDDDDRUDRLLURULRLDDLLRRURURDDRLLLULLULDDRDLDDDLRLLDRLDRUURRULURDDRLULLDUURRULURUUDULLRUDDRRLLDLLRDRUDDDDLLLDDDLLUUUULLDUUURULRUUDUUUDDLDURLDRDRRLLUDULDLUDRLLLDRRRULUUDDURUDRLUDDRRLLDUDUURDDRURLUURDURURURRUUDUDDLLLDRRRURURRURDLRULLDUDRLRLLRUDRUDLR";
		String commandoLista4 = "RRRDRLRURLRRLUURDRLDUURURLRDRRUDLLUUDURULLUURDLLDRRLURRUDUUDRRURLRRDULLDDLRRRUDUUDUUDLDDDLUUDLDULDDULLDUUUUDDUUDUDULLDDURRDLRRUDUDLRDUULDULRURRRLDLLURUDLDDDRRLRDURDLRRLLLRUDLUDRLLLRLLRRURUDLUDURLDRLRUDLRUULDRULLRLDRDRRLDDDURRRUDDDUDRRDRLDDRDRLLRLLRDLRDUDURURRLLULRDRLRDDRUULRDDRLULDLULURDLRUDRRDDDLDULULRDDRUDRLRDDRLDRDDRRRDUURDRLLDDUULRLLLULLDRDUDRRLUUURLDULUUURULLRLUDLDDLRRDLLRDDLRDRUUDURDDLLLDUUULUUDLULDUDULDRLRUDDURLDDRRRDLURRLLRRRUDDLDDRURDUULRUURDRRURURRRUUDUDULUDLUDLLLUUUULRLLRRRRDUDRRDRUDURLUDDLDRDLDDRULLRRULDURUL";
		String commandoLista5 = "DLLLRDDURDULRRLULURRDULDLUDLURDDURRLLRRLLULRDLDRDULRLLRDRUUULURRRLLRLDDDRDRRULDRRLLLLDLUULRRRURDDRULLULDDDLULRLRRRUDRURULUDDRULDUDRLDRRLURULRUULLLRUURDURLLULUURUULUUDLUDLRRULLLRRLRURDRRURDRULRURRUDUDDDRDDULDLURUDRDURLDLDLUDURLLRUULLURLDDDURDULRLUUUDLLRRLLUURRDUUDUUDUURURDRRRRRRRRRUDULDLULURUDUURDDULDUDDRDDRDRLRUUUUDLDLRDUURRLRUUDDDDURLRRULURDUUDLUUDUUURUUDRURDRDDDDULRLLRURLRLRDDLRUULLULULRRURURDDUULRDRRDRDLRDRRLDUDDULLDRUDDRRRD";

	
		keypad.moveCommandList(Arrays.asList(commandoLista1.split("")));
		System.out.println("Code 1: " + keypad.getCurrentKey());		
		keypad.moveCommandList(Arrays.asList(commandoLista2.split("")));
		System.out.println("Code 2: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista3.split("")));
		System.out.println("Code 3: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista4.split("")));
		System.out.println("Code 4: " + keypad.getCurrentKey());
		keypad.moveCommandList(Arrays.asList(commandoLista5.split("")));
		System.out.println("Code 5: " + keypad.getCurrentKey());
		
		
	}
	
}
